# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fcmiospush' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for fcmiospush
  pod 'Firebase/Messaging'
  

  pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

end
